version: '3.5'
services:
  sftpgo:
    image: drakkan/sftpgo
    container_name: sftpgo-${USER}
    ports:
      - '8080:8080'
      - '2022:2022'
      - '2121:2121'
      - '8090:8090'
      - '50000-50100:50000-50100'
    env_file: sftpgo.env
    volumes:
      - ./:/srv/sftpgo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db-${USER}
    env_file: sftpgo.env
    environment:
      POSTGRES_USER: "${SFTPGO_DATA_PROVIDER__USERNAME}"
      POSTGRES_PASSWORD: "${SFTPGO_DATA_PROVIDER__PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20